# @name get-prompts
GET http://localhost:3333/prompts

###

# @name get-prompts
GET http://localhost:3333/prompts
Content-Type: application/json

{
  "prompt": "clean architecture, ddd"
}

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/c7238af2-83ff-4397-9f2d-5caa8008fe9d/transcription
Content-Type: application/json

{
  "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "c7238af2-83ff-4397-9f2d-5caa8008fe9d",
  "temperature": 0.5,
  "prompt": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}

###

# @name get-videos
GET http://localhost:3333/videos
